name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2      # Checkout the repo
    - uses: actions/setup-python@v1  # Install the pythons
      with:
        python-version: ${{ matrix.python-version }}  # Install with matrix
        architecture: x64
    - run: pip install nox==2020.5.24
    - run: nox